/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.cursorwindow;

import android.database.CursorWindow;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import java.lang.reflect.Field;

@Kroll.module(name = "TiCursorwindow", id = "ti.cursorwindow")
public class TiCursorwindowModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "TiCursorwindowModule";

    public TiCursorwindowModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {}

    @Kroll.method
    public void init(int value) {
        try {
            Field field = CursorWindow.class.getDeclaredField("sCursorWindowSize");
            field.setAccessible(true);
            field.set(null, value);
            Log.d(LCAT, "Set cursor size to " + value);
        } catch (Exception e) {
            Log.e(LCAT, "Error: " + e.getMessage());
        }
    }

}
